package com.koukakios.intellijassist

class MockAiClient : AiClient {
    override fun ask(prompt: String): String {
        return """
            [Mock AI response]
            This is a placeholder response generated by MockAiClient.
            The real implementation should call an AI provider and return a contextual explanation.

            Prompt used:
            $prompt
        """.trimIndent()
    }
}
